"""Reproduce vanilla FeatureSorter.buildFeaturesPerStep for the overworld.

The biome order is the first appearance of Biomes constants while walking the
addBiomes call tree in the decompiled OverworldBiomeBuilder source.  Unlike a
lexical file sort, this preserves the order used by MultiNoiseBiomeSource.
"""
import json
import pathlib
import sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
BIOME_DIR = ROOT / "target/datapack/data/minecraft/worldgen/biome"
DECOMP = ROOT / "target/mache/versions/26.2/build/mache/input/decomp.jar"
PARAMETERS_REPORT = ROOT / "target/datagen/reports/biome_parameters/minecraft/overworld.json"
STEP = 6


def overworld_biomes():
    """Return biome JSON feature lists in OverworldBiomeBuilder order.

    The source's add* methods are deterministic nested loops.  For the purpose
    of first-encounter order, constants in the executable add* region give the
    same order as the builder; lookup-table declarations at the top are
    deliberately excluded.  Keep only names that have a datapack biome.
    """
    import zipfile
    with zipfile.ZipFile(DECOMP) as z:
        src = z.read("net/minecraft/world/level/biome/OverworldBiomeBuilder.java").decode()
    start = src.index("void addBiomes(")
    end = src.index("private ResourceKey<Biome> pickMiddleBiome", start)
    # Ensure the report is paired with the expected builder implementation;
    # its parameter insertion order is the actual MultiNoise possibleBiomes()
    # order and includes values selected indirectly by picker methods.
    if end <= start:
        raise RuntimeError("invalid OverworldBiomeBuilder source")
    available = {p.stem: json.loads(p.read_text(encoding="utf-8"))
                 for p in BIOME_DIR.glob("*.json")}
    # generated overworld report is that exact list, including helper-selected
    # biomes whose names are held in lookup arrays/locals in the Java source.
    ordered = []
    report = json.loads(PARAMETERS_REPORT.read_text(encoding="utf-8"))
    for entry in report["biomes"]:
        key = entry["biome"].split(":", 1)[-1]
        if key in available and key not in ordered:
            ordered.append(key)
    return [(name, available[name].get("features", [])) for name in ordered]


def build_order(biomes):
    feature_index = {}
    next_index = 0
    edges = {}  # (step, first-encounter index) -> set of same keys
    max_step = 0

    def key_for(name, step):
        nonlocal next_index
        if name not in feature_index:
            feature_index[name] = next_index
            next_index += 1
        return (step, feature_index[name], name)

    for _, steps in biomes:
        max_step = max(max_step, len(steps))
        flat = []
        for step, features in enumerate(steps):
            flat.extend(key_for(name, step) for name in features)
        for i, node in enumerate(flat):
            edges.setdefault(node, set())
            if i + 1 < len(flat):
                edges[node].add(flat[i + 1])

    # Graph.depthFirstSearch invokes the finish callback on post-order.
    discovered, visiting, post = set(), set(), []
    def dfs(node):
        if node in visiting:
            raise RuntimeError("feature order cycle")
        if node in discovered:
            return
        visiting.add(node)
        for nxt in sorted(edges[node], key=lambda x: (x[0], x[1])):
            dfs(nxt)
        visiting.remove(node)
        discovered.add(node)
        post.append(node)
    for node in sorted(edges, key=lambda x: (x[0], x[1])):
        if node not in discovered:
            dfs(node)
    post.reverse()
    return [[n[2] for n in post if n[0] == step] for step in range(max_step)]


def main():
    biomes = overworld_biomes()
    steps = build_order(biomes)
    order = steps[STEP]
    print(f"// {len(biomes)} overworld biomes, {len(order)} unique features in step {STEP}")
    for i, name in enumerate(order):
        print(f"{i:3}  {name}")
    if "--rust" in sys.argv:
        print("\n// generated by scripts/feature_sorter_order.py")
        print("pub const UNDERGROUND_ORES_ORDER: &[&str] = &[")
        for name in order:
            print(f'    "{name}",')
        print("];\n")


if __name__ == "__main__":
    main()
