"""Reproduce vanilla `FeatureSorter.buildFeaturesPerStep` for one generation step.

Vanilla assigns each `PlacedFeature` a global index per step by:
  1. walking every possible biome, numbering features by first encounter
     (`featureIndex.computeIfAbsent(feature, -> nextFeatureIndex++)`),
  2. adding an edge from each feature to its biome-local successor,
  3. depth-first-searching the edge map (ordered by `(step, featureIndex)`),
     appending on post-visit, then reversing the whole list.

`setFeatureSeed(decorationSeed, globalIndexOfFeature, stepIndex)` uses the
resulting position, so ore placement cannot match vanilla without it.

Emits a Rust array so `features.rs` can carry the real indices.
"""

import json
import glob
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BIOME_DIR = ROOT / "target/datapack/data/minecraft/worldgen/biome"
STEP = 6  # GenerationStep.Decoration.UNDERGROUND_ORES

# `BiomeSource.possibleBiomes()` for the overworld preset. Vanilla backs this with
# a Set, and the sort in step 3 makes the result independent of that set's order
# for our purposes, but the *first-encounter numbering* is not — so use the
# datapack's own lexicographic file order, which matches the registry order that
# MultiNoiseBiomeSource builds from the preset.
def overworld_biomes():
    out = {}
    for path in sorted(glob.glob(str(BIOME_DIR / "*.json"))):
        data = json.loads(pathlib.Path(path).read_text(encoding="utf-8"))
        steps = data.get("features", [])
        if len(steps) > STEP and "minecraft:ore_coal_upper" in steps[STEP]:
            out[pathlib.Path(path).stem] = steps
    return out


def build_order(biomes):
    feature_index = {}
    next_index = [0]

    def index_of(name):
        if name not in feature_index:
            feature_index[name] = next_index[0]
            next_index[0] += 1
        return feature_index[name]

    edges = {}
    for steps in biomes.values():
        local = [index_of(name) for name in steps[STEP]]
        for i, node in enumerate(local):
            succ = edges.setdefault(node, set())
            if i < len(local) - 1:
                succ.add(local[i + 1])

    # DFS in `(step, featureIndex)` order; step is constant here, so featureIndex.
    discovered, visiting, sorted_nodes = set(), set(), []

    def dfs(node):
        if node in discovered:
            return False
        if node in visiting:
            return True  # cycle
        visiting.add(node)
        for succ in sorted(edges.get(node, ())):
            if dfs(succ):
                return True
        visiting.discard(node)
        discovered.add(node)
        sorted_nodes.append(node)
        return False

    for node in sorted(edges):
        if node not in discovered:
            if dfs(node):
                raise SystemExit("feature order cycle")

    sorted_nodes.reverse()
    by_index = {v: k for k, v in feature_index.items()}
    return [by_index[n] for n in sorted_nodes]


def main():
    biomes = overworld_biomes()
    order = build_order(biomes)
    print(f"// {len(biomes)} overworld biomes, {len(order)} features in step {STEP}")
    for i, name in enumerate(order):
        print(f"{i:3}  {name}")

    if "--rust" in sys.argv:
        print("\n// generated by scripts/feature_sorter_order.py")
        print("pub const UNDERGROUND_ORES_ORDER: &[&str] = &[")
        for name in order:
            print(f'    "{name}",')
        print("];")


if __name__ == "__main__":
    main()
