#!/usr/bin/env python3
"""Block-for-block Overworld parity runner for BCore and vanilla.

The vanilla side is the terrain capture produced by capture_terrain.py.  The
BCore side is generated by the dump_chunk example.  State IDs are never
compared as opaque numbers: both are canonicalised through blocks.json names.

Examples:
  python scripts/parity_suite.py --chunk -34,3
  python scripts/parity_suite.py --radius 8 --seed 1234
  python scripts/parity_suite.py --vanilla path/to/capture.bin --no-build
"""
from __future__ import annotations
import argparse, json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CAPTURE = ROOT / "crates/bcore-protocol/data/vanilla_terrain_chunks.bin"
REPORT = ROOT / "target/datagen/reports/blocks.json"
MIN_Y = -64

# Names emitted by bcore_worldgen::block.  Keeping this table here makes the
# boundary explicit and catches accidental drift from the report IDs.
BCORE_IDS = {
    "air": 0, "stone": 1, "grass_block": 9, "dirt": 10,
    "coarse_dirt": 11, "podzol": 13, "bedrock": 85, "water": 86,
    "sand": 118, "gravel": 124, "gold_ore": 129, "iron_ore": 131,
    "coal_ore": 133, "copper_ore": 27790, "oak_log": 137,
    "oak_leaves": 255, "birch_log": 143, "birch_leaves": 311,
    "spruce_log": 149, "spruce_leaves": 367, "lapis_ore": 563,
    "sandstone": 578, "short_grass": 2248, "dead_bush": 2250,
    "diamond_ore": 5307, "redstone_ore": 6882, "snow_block": 6928,
    "cactus": 6929, "deepslate": 30417,
}


def load_codec() -> tuple[dict[int, str], dict[str, int]]:
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    id_to_name: dict[int, str] = {}
    for name, entry in report.items():
        for state in entry.get("states", []):
            id_to_name[int(state["id"])] = name
    name_to_bcore = {"minecraft:" + name: value for name, value in BCORE_IDS.items()}
    missing = [name for name, value in name_to_bcore.items()
               if value not in id_to_name or id_to_name[value] != name]
    if missing:
        raise RuntimeError("blocks.json does not describe BCore IDs: " + ", ".join(missing))
    return id_to_name, name_to_bcore


def decode_capture(path: pathlib.Path) -> dict[tuple[int, int], list[int]]:
    # Reuse the already-tested wire decoder, rather than maintaining a second
    # packet implementation here.
    sys.path.insert(0, str(ROOT / "scripts"))
    import analyze_terrain_capture as decoder
    data = path.read_bytes()
    out = {}
    for _, payload in decoder.packets(data):
        chunk = decoder.decode(payload)
        states: list[int] = []
        for section in chunk["sections"]:
            states.extend(section["states"])
        out[(chunk["x"], chunk["z"])] = states
    return out


def run_bcore(seed: int, coords: list[tuple[int, int]], no_build: bool) -> dict[tuple[int, int], list[int]]:
    result = {}
    for cx, cz in coords:
        cmd = ["cargo", "run", "-q", "-p", "bcore-worldgen", "--example", "dump_chunk"]
        if no_build:
            cmd[1:3] = ["run", "-q"]  # cargo still resolves an existing target
        proc = subprocess.run(cmd + ["--", str(seed), str(cx), str(cz)], cwd=ROOT,
                              text=True, capture_output=True, check=True)
        result[(cx, cz)] = json.loads(proc.stdout)["states"]
    return result


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=1234)
    ap.add_argument("--radius", type=int, default=8)
    ap.add_argument("--chunk", action="append", metavar="X,Z", help="repeatable explicit chunk")
    ap.add_argument("--vanilla", type=pathlib.Path, default=CAPTURE)
    ap.add_argument("--max-diffs", type=int, default=20)
    ap.add_argument("--no-build", action="store_true", help="kept for CLI compatibility")
    args = ap.parse_args()
    try:
        id_to_name, name_to_bcore = load_codec()
        vanilla = decode_capture(args.vanilla)
        wanted = [(int(x), int(z)) for value in args.chunk for x, z in [value.split(",")]] if args.chunk else sorted(vanilla)
        if args.chunk:
            wanted = [c for c in wanted if c in vanilla]
        elif args.radius:
            wanted = [c for c in wanted if abs(c[0]) <= args.radius and abs(c[1]) <= args.radius]
        if not wanted:
            print("No requested chunks are present in the vanilla capture.", file=sys.stderr)
            return 2
        bcore = run_bcore(args.seed, wanted, args.no_build)
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError, RuntimeError) as exc:
        print(f"parity setup failed: {exc}", file=sys.stderr)
        return 2

    chunks_ok = columns_ok = blocks_ok = total_columns = total_blocks = 0
    diffs = []
    for coord in wanted:
        v = vanilla[coord]; b = bcore[coord]
        if len(v) != len(b):
            print(f"chunk {coord}: length vanilla={len(v)} bcore={len(b)}", file=sys.stderr)
            continue
        chunk_good = True
        for index, (vi, bi) in enumerate(zip(v, b)):
            total_blocks += 1
            if vi == bi or id_to_name.get(vi) == id_to_name.get(bi):
                blocks_ok += 1
            else:
                chunk_good = False
                col = (index // 256) % 16, (index // 4096) % 16
                y = MIN_Y + index // 256
                if len(diffs) < args.max_diffs:
                    diffs.append((coord, col, y, vi, bi, id_to_name.get(vi, "<unknown>"), id_to_name.get(bi, "<unknown>")))
        for col in range(256):
            total_columns += 1
            if all(v[y * 256 + col] == b[y * 256 + col] or id_to_name.get(v[y * 256 + col]) == id_to_name.get(b[y * 256 + col]) for y in range(len(v) // 256)):
                columns_ok += 1
        if chunk_good: chunks_ok += 1
    pct = lambda n, d: 100.0 * n / d if d else 0.0
    print(f"chunks: {chunks_ok}/{len(wanted)} ({pct(chunks_ok,len(wanted)):.2f}%)")
    print(f"columns: {columns_ok}/{total_columns} ({pct(columns_ok,total_columns):.2f}%)")
    print(f"blocks: {blocks_ok}/{total_blocks} ({pct(blocks_ok,total_blocks):.2f}%)")
    print("first differences:")
    for c, col, y, vi, bi, vn, bn in diffs:
        print(f"  chunk={c} column={col} y={y} vanilla={vi}:{vn} bcore={bi}:{bn}")
    return 0 if chunks_ok == len(wanted) else 1

if __name__ == "__main__":
    raise SystemExit(main())
